#!/bin/bash
#
#              INGLÊS/ENGLISH
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  http://www.gnu.org/copyleft/gpl.html
#
#
#             PORTUGUÊS/PORTUGUESE
#  Este programa é distribuído na expectativa de ser útil aos seus
#  usuários, porém NÃO TEM NENHUMA GARANTIA, EXPLÍCITAS OU IMPLÍCITAS,
#  COMERCIAIS OU DE ATENDIMENTO A UMA DETERMINADA FINALIDADE.  Consulte
#  a Licença Pública Geral GNU para maiores detalhes.
#  http://www.gnu.org/copyleft/gpl.html
#
#  Copyright (C) 2018  Universidade Estadual Paulista - UNESP
#
#  Universidade Estadual Paulista "Júlio de Mesquita Filho"
#  Laboratório de Bioinformática
#
#  Rafael Correia da Silva
#  rcs.biotec@gmail.com
#

## Pipe: da anotação até o biom
# Implementado: blast e vsearch, resta classificador
# Resta implementar:
# 0. Export visual da diversidade beta do QIIME2
# 1. Feature-classifier
# 3. Pré-processamento

# Obtem os parâmetros
echo "Grabbing parameters..."
source intel/parameters.txt

echo "Test directory is: ${testdir}"
## Criando as pastas
mkdir -p ${testdir}
mkdir -p ${testdir}/rarefied
mkdir -p ${testdir}/unrare
mkdir -p ${testdir}/useful

## Limpa o log, cria novamente
echo "Restarting log..."
rm -f ${testdir}/run_report
touch ${testdir}/run_report

## [.. Clusterização de novo ..] ##
## Roda a clusterização de novo caso tenha solicitado ##
if [[ ${denovo} = "yes" ]]; then

	echo "Beginning de novo clusterization..."
	echo

	if [ ! -f ${seqsdir}/${table_seqs} ]; then
	
		mkdir -p ${seqsdir}

		qiime vsearch cluster-features-open-reference \
			--i-sequences ${artdir}/${rep_seqs} \
			--i-table ${artdir}/${table_seqs} \
			--i-reference-sequences ${ref_seqs} \
			--p-perc-identity ${parameter_cluster_id} \
			--p-threads ${parameter_threads} \
			--o-clustered-table ${seqsdir}/${table_seqs} \
			--o-clustered-sequences ${seqsdir}/${rep_seqs} \
			--o-new-reference-sequences ${seqsdir}/${testname}.new_refs.qza \
			--verbose

		echo "Writing de novo cluster changes..."
	fi

else
		
	# Define o diretório de sequências como o mesmo dos artefatos
	# Caso a anotação não seja a denovo, a entrada das sequências
	# será a mesma em que se encontram os artefatos gerados pelo
	# pré-processamento
	seqsdir=$(echo ${artdir})

fi

	## Classifies if taxonomy.qza doesnt exist

if [ ! -f ${testdir}/taxonomy.qza ]; then

## Opção: VSEARCH

	if [[ $annotator = "vsearch" ]]; then

		echo "Starting taxonomy assignment..."
	        echo "Program: VSEARCH"
		echo "Identity: ${parameter_identity}"
		echo "Reference reads: ${ref_seqs}"
		echo "Reference taxonomy: ${ref_tax}"
		echo "Threads: ${parameter_threads}"
		
		qiime feature-classifier classify-consensus-vsearch \
		    	--i-query ${seqsdir}/${rep_seqs} \
	    		--i-reference-reads ${ref_seqs} \
			--i-reference-taxonomy ${ref_tax} \
			--p-threads ${parameter_threads} \
			--p-perc-identity ${parameter_identity} \
			--o-classification ${testdir}/taxonomy.qza \
		    	--verbose
	fi

				
## Opção: BLAST

	if [[ $annotator = "blast" ]]; then
	
		echo "Starting taxonomy assignment..."
	        echo "Program: BLAST"
		echo "Identity: ${parameter_identity}"
		echo "Reference reads: ${ref_seqs}"
		echo "Reference taxonomy: ${ref_tax}"


	qiime feature-classifier classify-consensus-blast \
		--i-query ${seqsdir}/${rep_seqs} \
		--i-reference-reads ${ref_seqs} \
		--i-reference-taxonomy ${ref_tax} \
		--p-perc-identity ${parameter_identity} \
		--o-classification ${testdir}/taxonomy.qza \
	       	--verbose

	fi

else
	echo "Taxonomy file already exists for ${testdir}, skipping..."

fi

														    
# 3. Filtering chloroplasts and mitochondria

echo "Filtering chloroplasts and mitochondria..."

qiime taxa filter-table \
	--i-table ${seqsdir}/${table_seqs} \
	--i-taxonomy ${testdir}/taxonomy.qza \
	--p-exclude Mitochondria,Chloroplast \
	--o-filtered-table ${testdir}/pure-table.qza

        
# 4. Saída: arquivo BIOM não rarefeito

echo "Exporting BIOM table: unrarefied"
echo

qiime tools export \
	--input-path ${testdir}/pure-table.qza \
	--output-path ${testdir}/unrare


# Exportar a referência de taxonomia

echo "Exporting taxonomy reference..."
echo

qiime tools export \
	--input-path ${testdir}/taxonomy.qza \
	--output-path ${testdir}


if [[ ${choosen_database} = "SILVA" ]]; then

echo "Fixing OTU table headers (SILVA database)"

        ## Fixa o cabeçalho da OTU Table
        cp ${testdir}/taxonomy.tsv ${testdir}/useful/taxonomy-no-headers.tsv
        cat ${testdir}/taxonomy.tsv | sed 1d > ${testdir}/taxtemp.tsv

	if [[ ! -f ${testdir}/taxtemp.tsv ]]; then
		echo "Taxonomy not converted. Aborting..."
		exit
	fi


        echo
        echo "Formatting SILVA taxonomy table to Microbiome Analyst..."
        echo

        # Remove os delimitadores do banco de dados SILVA (D_{0|1|2|3})
        # Deixando-os limpos para downstream (HCRP)

	# Part I: fixing taxa prefixes...

                cat ${testdir}/taxtemp.tsv | sed 's/D_0__//' | \
                sed 's/D_1__//' | \
                sed 's/D_2__//' | \
                sed 's/D_3__//' | \
                sed 's/D_4__//' | \
                sed 's/D_5__//' | \
                sed 's/D_6__//' | sed 's/;/; /g' > ${testdir}/taxtemp.tsv

	# Part II: fixing header...

                sed -i '1 i\#OTUID\ttaxonomy\tconfidence' ${testdir}/taxtemp.tsv
                mv ${testdir}/taxtemp.tsv ${testdir}/formatted.tsv

        # Cria uma cópia no useful, e outra para continuar a análise
        cp ${testdir}/formatted.tsv ${testdir}/useful/taxonomy-downstream.tsv
        mv ${testdir}/formatted.tsv ${testdir}/taxonomy.tsv
#	rm ${testdir}/taxtemp.tsv

else
	echo "Fixing taxonomy table headers (other databases)"
	## Fixa o cabeçalho da OTU Table para qualquer outro banco
	cat ${testdir}/taxonomy.tsv | sed 1d > /tmp/taxtemp.tsv
	sed -i '1 i\#OTUID\ttaxonomy\tconfidence' /tmp/taxtemp.tsv
	rm ${testdir}/taxonomy.tsv
	mv /tmp/taxtemp.tsv ${testdir}/taxonomy.tsv
	head ${testdir}/taxonomy.tsv
fi

## Sumarizando o experimento - contagens

echo "Summarizing counts..."
qiime feature-table summarize \
	    --i-table ${testdir}/pure-table.qza \
	    --o-visualization ${testdir}/pure-table.qzv \
	    --m-sample-metadata-file intel/metadata.tsv
    
echo "Exporting HTML for counts..."
echo
## Exportando HTML
qiime tools export \
	--input-path ${testdir}/pure-table.qzv \
	--output-path ${testdir}/pure-table-html


# Obtendo o valor de rarefação

echo "Getting rarefaction value..."
rarevalue=`tail -1 ${testdir}/pure-table-html/sample-frequency-detail.csv | sed 's/.*,//' | sed 's/\..//'`
tail -15 ${testdir}/pure-table-html/sample-frequency-detail.csv
echo "Rarefaction is: ${rarevalue}"
echo
	
## Rarefação
echo "Rarefying feature table..."
qiime feature-table rarefy \
	--i-table ${testdir}/pure-table.qza \
	--p-sampling-depth ${rarevalue} \
	--o-rarefied-table ${testdir}/rarefied/rare-table.qza
	
## Exportando a tabela biom rarefeita
echo "Exporting the rarefied BIOM..."
qiime tools export \
		--input-path ${testdir}/rarefied/rare-table.qza \
		--output-path ${testdir}/rarefied

echo "Adding taxonomy to BIOM (rarefied)..."
## Juntando biom e taxonomia
biom add-metadata \
		-i ${testdir}/rarefied/feature-table.biom \
		-o ${testdir}/rarefied/tabletax-rare.biom \
		--observation-metadata-fp ${testdir}/taxonomy.tsv \
		--sc-separated taxonomy
	
echo "Adding taxonomy to BIOM (raw)..."
biom add-metadata \
		-i ${testdir}/unrare/feature-table.biom \
		-o ${testdir}/unrare/tabletax-unrare.biom \
		--observation-metadata-fp ${testdir}/taxonomy.tsv \
		--sc-separated taxonomy
	
echo "Generating OTU tables (feature-table.biom)"
## Gerando as OTU tables (sem nomes)
biom convert -i ${testdir}/unrare/feature-table.biom -o ${testdir}/unrare/otu_table.txt --to-tsv
biom convert -i ${testdir}/rarefied/feature-table.biom -o ${testdir}/rarefied/otu_table.txt --to-tsv


echo "Generating tabulated BIOM files"	
## Gerar planilhas (1) rarefeitas (2) não rarefeitas
./modules/summarize_taxa.py --absolute_abundance -i ${testdir}/rarefied/tabletax-rare.biom -o ${testdir}/rarefied/tabulated
./modules/summarize_taxa.py --absolute_abundance -i ${testdir}/unrare/tabletax-unrare.biom -o ${testdir}/unrare/tabulated

if [[ ${run_diversity} = "yes" ]]; then

	# Core-metrics: phylogeny
	if [ ! -f ${artdir}/${testname}.rooted-tree.qza ]; then
		qiime phylogeny align-to-tree-mafft-fasttree \
			--i-sequences ${seqsdir}/${rep_seqs} \
			--o-alignment ${artdir}/${testname}.aligned-rep-seqs.qza \
			--o-masked-alignment ${artdir}/${testname}.masked-aligned-rep-seqs.qza \
			--o-tree ${artdir}/${testname}.unrooted-tree.qza \
			--o-rooted-tree ${artdir}/${testname}.rooted-tree.qza \
			--verbose
	fi

	## Core	diversity
	echo "Running core metrics..."

	qiime diversity core-metrics-phylogenetic \
		--i-phylogeny ${artdir}/${testname}.rooted-tree.qza \
		--i-table ${testdir}/pure-table.qza \
		--p-sampling-depth ${rarevalue} \
		--m-metadata-file ${inteldir}/metadata.tsv \
		--output-dir ${testdir}/core-metrics-results

	# Cria a rarefação máxima
	maxrare=$((10*${rarevalue}))

	## Alpha diversity
	qiime diversity alpha-rarefaction \
		--i-table ${testdir}/pure-table.qza \
		--i-phylogeny ${artdir}/${testname}.rooted-tree.qza \
		--p-max-depth ${maxrare} \
		--m-metadata-file ${inteldir}/metadata.tsv \
		--o-visualization ${testdir}/alpha-rarefaction.qzv

	## Exportando HTML
	qiime tools export \
		--input-path ${testdir}/alpha-rarefaction.qzv \
		--output-path ${testdir}/alpha-rarefaction
	
	qiime tools export \
		--input-path ${testdir}/core-metrics-results/jaccard_emperor.qzv \
		--output-path ${testdir}/core-metrics-results/jaccard_emperor
		
	qiime tools export \
		--input-path ${testdir}/core-metrics-results/weighted_unifrac_emperor.qzv \
		--output-path ${testdir}/core-metrics-results/weighted_unifrac_emperor
		
	qiime tools export \
		--input-path ${testdir}/core-metrics-results/unweighted_unifrac_emperor.qzv \
		--output-path ${testdir}/core-metrics-results/unweighted_unifrac_emperor
	
	qiime tools export \
		--input-path ${testdir}/core-metrics-results/bray_curtis_emperor.qzv \
		--output-path ${testdir}/core-metrics-results/bray_curtis_emperor
fi
	
	
if [[ ${run_corrupt} = "yes" ]]; then
	
	## Exportando com cloroplastos e mitocôndria
	# Primeiro: exportando o BIOM
	mkdir -p ${testdir}/corrupt

	qiime tools export \
		--input-path ${seqsdir}/${table_seqs}  \
		--output-path ${testdir}/corrupt
	
	## Sumarizando o experimento - contagens
	qiime feature-table summarize \
	    --i-table ${seqsdir}/${table_seqs} \
	    --o-visualization ${testdir}/corrupt/corrupt-table.qzv \
	    --m-sample-metadata-file intel/metadata.tsv
	    
	## Exportando HTML
	qiime tools export \
		--input-path ${testdir}/corrupt/corrupt-table.qzv \
		--output-path ${testdir}/corrupt/corrupt-table-html
		
	# Obtendo o valor de rarefação
	corrupt_rarevalue=`tail -1 ${testdir}/corrupt/corrupt-table-html/sample-frequency-detail.csv | sed 's/.*,//' | sed 's/\..//'`
	tail -15 ${testdir}/corrupt/corrupt-table-html/sample-frequency-detail.csv
	echo "Rarefaction is: ${corrupt_rarevalue}"
	
	## Rarefação
	qiime feature-table rarefy \
		--i-table ${seqsdir}/${table_seqs} \
		--p-sampling-depth ${corrupt_rarevalue} \
		--o-rarefied-table ${testdir}/corrupt/rare-table.qza
	
	## Exportando a tabela biom rarefeita
	qiime tools export \
		--input-path ${testdir}/corrupt/rare-table.qza \
		--output-path ${testdir}/corrupt
	
	## Juntando biom e taxonomia
	biom add-metadata \
		-i ${testdir}/corrupt/feature-table.biom \
		-o ${testdir}/corrupt/tabletax-rare.biom \
		--observation-metadata-fp ${testdir}/taxonomy.tsv \
		--sc-separated taxonomy
	
	# Gera a OTU table convertida
	biom convert -i ${testdir}/corrupt/feature-table.biom -o ${testdir}/corrupt/otu_table.txt --to-tsv

	./modules/summarize_taxa.py --absolute_abundance -i ${testdir}/corrupt/tabletax-rare.biom -o ${testdir}/corrupt/tabulated

fi

# # # # # [. LOG SECTION .] # # # # # # # # #

# Reporting metrics

# 0. Parameters report:
echo "Parameters for this run were: " >> ${testdir}/run_report
echo "Did this run clusterized open reference? $denovo" >> ${testdir}/run_report
echo "What was the annotation program? $annotator" >> ${testdir}/run_report
echo "What was the identity (%) for annotation? $parameter_identity" >> ${testdir}/run_report

echo >> ${testdir}/run_report

# 1. OTU number
otu_lines=`wc ${testdir}/rarefied/otu_table.txt -l | sed 's/ .*//'`
otu_no_headers=`expr "$otu_lines" - 1`
echo "| -------- Core information for analysis ---------- |" >> ${testdir}/run_report
echo "Number of OTUs is: $otu_no_headers" >> ${testdir}/run_report

# 2. Unique genera
genera_lines=`wc ${testdir}/rarefied/tabulated/tabletax-rare_L6.txt -l | sed 's/ .*//'`
genera_no_headers=`expr "$genera_lines" - 1`
echo "Unique genera for analysis: $genera_no_headers" >> ${testdir}/run_report

# 3. Unique "Others"
unique_others=`grep "\;Other" ${testdir}/rarefied/tabulated/tabletax-rare_L6.txt | wc -l`
echo "OTUs not classified up to Genus (Other) were: ${unique_others}." >> ${testdir}/run_report

# 4. Number of Phylla
phylla_lines=`wc ${testdir}/rarefied/tabulated/tabletax-rare_L2.txt -l | sed 's/ .*//'`
phylla_no_headers=`expr "$phylla_lines" - 1`
echo "Unique phylla for analysis: $phylla_no_headers" >> ${testdir}/run_report

# 5. Rarefaction value
echo "The rarefaction value was: $rarevalue" >> ${testdir}/run_report

# 6. Were there Archaea?
if grep -q "Archaea" ${testdir}/rarefied/tabulated/tabletax-rare_L2.txt; then
	echo "Archaea were found in the analysis." >> ${testdir}/run_report
else
	echo "Archaea were not found in the analysis." >> ${testdir}/run_report
fi

# 7. Miscellaneous run information
echo "Run name: $testname" >> ${testdir}/run_report"

# Zip results
tar -zvcf output/"results.$testname.tar.gz" ${testdir}/rarefied ${testdir}/unrare ${testdir}/pure-table-html ${testdir}/core-metrics-results ${testdir}/alpha-rarefaction ${testdir}/run_report #${testdir}/corrupt

